import { ThemeProvider } from "@/context/ThemeContext/ThemeContext";
import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";
import ReduxProvider from "@/providers/ReduxProvider";
import ToastProvider from "@/components/common/Toast/ToastProvider";
import { GoogleOAuthProvider } from "@react-oauth/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeScript = `
  (function () {
    try {
      const savedTheme = localStorage.getItem("teamsync-theme");

      if (savedTheme === "light" || savedTheme === "dark") {
        document.documentElement.setAttribute(
          "data-theme",
          savedTheme
        );
      }
    } catch (error) {
      console.error("Failed to load saved theme", error);
    }
  })();
`;

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Script
          id="theme-script"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: themeScript }}
        />
        <ReduxProvider>
          <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_CLIENT_ID!}>
            <ThemeProvider>
              <ToastProvider>{children}</ToastProvider>
            </ThemeProvider>
          </GoogleOAuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
