// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using server.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace server.Models
{
    public partial interface ITeamSyncContextProcedures
    {
        Task<List<usp_CreateOrganizationResult>> usp_CreateOrganizationAsync(string name, string description, string logoUrl, int? createdByUserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_GetUserOrganizations_PagedResult>> usp_GetUserOrganizations_PagedAsync(int? userId, int? pageSize, string searchTerm, DateTime? lastJoinedAt, int? lastOrganizationId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_Organization_SoftDeleteResult>> usp_Organization_SoftDeleteAsync(int? organizationId, int? userId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_Organization_UpdateResult>> usp_Organization_UpdateAsync(int? organizationId, int? userId, string name, string description, string logoUrl, bool? updateLogo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
