// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace server.Models;

public partial class OrganizationMember
{
    public int OrganizationMemberId { get; set; }

    public int OrganizationId { get; set; }

    public int UserId { get; set; }

    public int RoleId { get; set; }

    public string MembershipStatus { get; set; }

    public DateTime JoinedAt { get; set; }

    public int? InvitedByUserId { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User InvitedByUser { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual OrganizationMemberRole Role { get; set; }

    public virtual User User { get; set; }
}