// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace server.Models;

public partial class Organization
{
    public int OrganizationId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string LogoUrl { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int CreatedByUserId { get; set; }

    public int? UpdatedByUserId { get; set; }

    public int? DeletedByUserId { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual User DeletedByUser { get; set; }

    public virtual ICollection<OrganizationMember> OrganizationMembers { get; set; } = new List<OrganizationMember>();

    public virtual User UpdatedByUser { get; set; }
}