// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using server.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace server.Models
{
    public partial class TeamSyncContext
    {
        private ITeamSyncContextProcedures _procedures;

        public virtual ITeamSyncContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new TeamSyncContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ITeamSyncContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class TeamSyncContextProcedures : ITeamSyncContextProcedures
    {
        private readonly TeamSyncContext _context;

        public TeamSyncContextProcedures(TeamSyncContext context)
        {
            _context = context;
        }

        public virtual async Task<List<usp_CreateOrganizationResult>> usp_CreateOrganizationAsync(string name, string description, string logoUrl, int? createdByUserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Name",
                    Size = 300,
                    Value = name ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Description",
                    Size = 1000,
                    Value = description ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "LogoUrl",
                    Size = 1000,
                    Value = logoUrl ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "CreatedByUserId",
                    Value = createdByUserId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<usp_CreateOrganizationResult>("EXEC @returnValue = [dbo].[usp_CreateOrganization] @Name = @Name, @Description = @Description, @LogoUrl = @LogoUrl, @CreatedByUserId = @CreatedByUserId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<usp_GetUserOrganizations_PagedResult>> usp_GetUserOrganizations_PagedAsync(int? userId, int? pageSize, string searchTerm, DateTime? lastJoinedAt, int? lastOrganizationId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "UserId",
                    Value = userId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PageSize",
                    Value = pageSize ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "SearchTerm",
                    Size = 200,
                    Value = searchTerm ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "LastJoinedAt",
                    Scale = 7,
                    Value = lastJoinedAt ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                new SqlParameter
                {
                    ParameterName = "LastOrganizationId",
                    Value = lastOrganizationId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<usp_GetUserOrganizations_PagedResult>("EXEC @returnValue = [dbo].[usp_GetUserOrganizations_Paged] @UserId = @UserId, @PageSize = @PageSize, @SearchTerm = @SearchTerm, @LastJoinedAt = @LastJoinedAt, @LastOrganizationId = @LastOrganizationId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<usp_Organization_SoftDeleteResult>> usp_Organization_SoftDeleteAsync(int? organizationId, int? userId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "OrganizationId",
                    Value = organizationId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "UserId",
                    Value = userId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<usp_Organization_SoftDeleteResult>("EXEC @returnValue = [dbo].[usp_Organization_SoftDelete] @OrganizationId = @OrganizationId, @UserId = @UserId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<usp_Organization_UpdateResult>> usp_Organization_UpdateAsync(int? organizationId, int? userId, string name, string description, string logoUrl, bool? updateLogo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "OrganizationId",
                    Value = organizationId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "UserId",
                    Value = userId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Name",
                    Size = 300,
                    Value = name ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Description",
                    Size = 1000,
                    Value = description ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "LogoUrl",
                    Size = 1000,
                    Value = logoUrl ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "UpdateLogo",
                    Value = updateLogo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<usp_Organization_UpdateResult>("EXEC @returnValue = [dbo].[usp_Organization_Update] @OrganizationId = @OrganizationId, @UserId = @UserId, @Name = @Name, @Description = @Description, @LogoUrl = @LogoUrl, @UpdateLogo = @UpdateLogo", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
