// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace server.Models;

public partial class User
{
    public int UserId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string ProfilePhoto { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? LastLoginAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public string GoogleId { get; set; }

    public string PasswordResetToken { get; set; }

    public DateTime? PasswordResetExpiry { get; set; }

    public virtual ICollection<Organization> OrganizationCreatedByUsers { get; set; } = new List<Organization>();

    public virtual ICollection<Organization> OrganizationDeletedByUsers { get; set; } = new List<Organization>();

    public virtual ICollection<OrganizationMember> OrganizationMemberInvitedByUsers { get; set; } = new List<OrganizationMember>();

    public virtual ICollection<OrganizationMember> OrganizationMemberUsers { get; set; } = new List<OrganizationMember>();

    public virtual ICollection<Organization> OrganizationUpdatedByUsers { get; set; } = new List<Organization>();
}